import { notFound } from "next/navigation";
import { normalizeLang, timeAgoHi, SUPPORTED_LANGS } from "@/lib/news";
import { getArticleBySlug, getRelated, getTranslation, saveTranslation } from "@/lib/db";
import { translateArticle } from "@/lib/ai";
import { CAT, Tag, hrefFor } from "@/components/ui";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import GenerateArticle from "@/components/GenerateArticle";
import ArticleBody from "@/components/ArticleBody";

export const dynamic = "force-dynamic";
export const maxDuration = 60; // background AI article generation runs via after()

const SITE = process.env.NEXT_PUBLIC_SITE_URL || "https://muddhadeshka.vercel.app";

export async function generateMetadata({ params }) {
  const { slug } = await params;
  const a = await getArticleBySlug(slug);
  if (!a) return { title: "मुद्दा देश का" };

  const title = a.meta_title || a.ai_title || a.title;
  const description = (a.meta_desc || a.full_content || a.summary || "").replace(/\s+/g, " ").slice(0, 160);
  const url = `${SITE}/khabar/${a.slug}`;
  const images = a.image ? [a.image] : [`${SITE}/logo.png`];

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title, description, url, type: "article", siteName: "मुद्दा देश का",
      locale: "hi_IN", images,
      publishedTime: a.published_at ? new Date(a.published_at).toISOString() : undefined,
    },
    twitter: { card: "summary_large_image", title, description, images },
  };
}

const VIEW_LANGS = [
  { code: "hi", label: "हिंदी" },
  { code: "hinglish", label: "Hinglish" },
  { code: "en", label: "English" },
];

export default async function ArticlePage({ params, searchParams }) {
  const { slug } = await params;
  const sp = await searchParams;
  let a = await getArticleBySlug(slug);
  if (!a) notFound();

  // The full original (multi-source merged) article is generated by AI (scrape + LLM).
  // It's normally pre-warmed by the background cron, so this is usually already set.
  // If not, the page renders the source summary instantly and a client component asks
  // the server to build it, then reloads — never blocking the initial render.
  const pending = !a.full_content;

  // UI language = ?lang (top-bar / toggle), falls back to the article's native lang
  const lang = sp?.lang && SUPPORTED_LANGS.includes(sp.lang) ? sp.lang : normalizeLang(a.lang);
  const mergedSources = Array.isArray(a.ai_sources) ? a.ai_sources : [];

  // View language toggle (हिंदी / Hinglish / English) — translate on demand + cache
  const viewLang = VIEW_LANGS.some((v) => v.code === lang) ? lang : a.lang;
  let dTitle = a.ai_title || a.title;
  let dBody = a.full_content || a.summary || "";
  let dPoints = Array.isArray(a.key_points) ? a.key_points : [];
  if (viewLang !== a.lang && a.full_content) {
    let t = await getTranslation(slug, viewLang);
    if (!t) {
      try {
        const r = await translateArticle({ title: dTitle, body: dBody, keyPoints: dPoints, targetLang: viewLang });
        await saveTranslation(slug, viewLang, r);
        t = { title: r.title, body: r.body, key_points: r.keyPoints };
      } catch { /* translation failed → show native */ }
    }
    if (t) { dTitle = t.title || dTitle; dBody = t.body || dBody; dPoints = Array.isArray(t.key_points) ? t.key_points : dPoints; }
  }

  const points = dPoints;
  const related = await getRelated({ lang, category: a.category, excludeSlug: slug, limit: 6 });
  const catLabel = CAT[a.category]?.label || "";

  const published = a.published_at ? new Date(a.published_at).toISOString() : undefined;
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    headline: (a.ai_title || a.title || "").slice(0, 110),
    description: (a.meta_desc || a.summary || "").replace(/\s+/g, " ").slice(0, 200),
    image: a.image ? [a.image] : [`${SITE}/logo.png`],
    datePublished: published,
    dateModified: a.ai_at ? new Date(a.ai_at).toISOString() : published,
    inLanguage: lang,
    author: { "@type": "Organization", name: "मुद्दा देश का" },
    publisher: {
      "@type": "Organization",
      name: "मुद्दा देश का",
      logo: { "@type": "ImageObject", url: `${SITE}/logo.png` },
    },
    mainEntityOfPage: { "@type": "WebPage", "@id": `${SITE}/khabar/${a.slug}` },
  };

  return (
    <div className="min-h-full bg-zinc-100 text-zinc-900">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <SiteHeader lang={lang} basePath="/" activeCat={a.category} />

      <main className="mx-auto max-w-3xl px-4 py-6">
        {/* Breadcrumb */}
        <nav className="mb-3 text-xs text-zinc-500">
          <a href={hrefFor("/", lang)} className="hover:text-brand-blue">होम</a>
          {catLabel && <> · <a href={hrefFor(`/${a.category}`, lang)} className="hover:text-brand-blue">{catLabel}</a></>}
        </nav>

        <article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-zinc-200 sm:p-7">
          <Tag slug={a.category} />
          <h1 className="mt-2 text-2xl font-extrabold leading-tight text-zinc-900 sm:text-3xl">
            {dTitle}
          </h1>
          <div className="mt-2 flex flex-wrap items-center gap-3 text-sm text-zinc-500">
            <span>{timeAgoHi(a.published_at)}</span>
            <span className="flex items-center gap-1">
              <span className="text-xs text-zinc-400">पढ़ें:</span>
              {VIEW_LANGS.map((v) => (
                <a key={v.code} href={`?lang=${v.code}`}
                   className={`rounded px-2 py-0.5 text-xs font-medium transition ${
                     v.code === viewLang ? "bg-brand-blue text-white" : "bg-zinc-100 text-zinc-600 hover:bg-zinc-200"
                   }`}>
                  {v.label}
                </a>
              ))}
            </span>
          </div>

          {a.image && (
            <img src={a.image} alt="" className="mt-4 w-full rounded-lg object-cover" />
          )}

          {/* Full AI article still generating in the background → reload when ready */}
          {pending && (
            <>
              <GenerateArticle slug={slug} />
              <div className="mt-5 flex items-center gap-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
                <span className="h-4 w-4 shrink-0 animate-spin rounded-full border-2 border-amber-400 border-t-transparent" />
                <span>पूरी विस्तृत खबर तैयार की जा रही है — यह पेज कुछ ही क्षण में अपने आप अपडेट हो जाएगा।</span>
              </div>
            </>
          )}

          {/* Key points */}
          {points.length > 0 && (
            <div className="mt-5 rounded-lg border-l-4 border-brand-red bg-rose-50/60 p-4">
              <p className="mb-2 text-sm font-bold text-brand-red">मुख्य बातें</p>
              <ul className="space-y-1.5 text-sm text-zinc-700">
                {points.map((p, i) => (
                  <li key={i} className="flex gap-2"><span className="text-brand-red">•</span><span>{p}</span></li>
                ))}
              </ul>
            </div>
          )}

          {/* Body */}
          <div className="mt-5">
            <ArticleBody text={dBody} />
          </div>

          {/* Source button */}
          <div className="mt-6 border-t border-zinc-200 pt-5">
            <a href={a.source_url} target="_blank" rel="noopener noreferrer"
               className="inline-flex items-center gap-2 rounded-lg bg-brand-blue px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-brand-blue-dark">
              मूल स्रोत पर पूरी खबर पढ़ें →
            </a>
            <p className="mt-3 text-xs text-zinc-400">
              यह खबर AI द्वारा {mergedSources.length > 1 ? `${mergedSources.join(", ")} की रिपोर्ट्स के आधार पर` : "मूल स्रोत के आधार पर"} तैयार की गई है।
            </p>
          </div>
        </article>

        {/* Related */}
        {related.length > 0 && (
          <section className="mt-8">
            <h2 className="mb-3 flex items-center gap-2 text-lg font-extrabold">
              <span className="h-5 w-1.5 rounded bg-brand-red" /> इसे भी पढ़ें
            </h2>
            <div className="grid gap-4 sm:grid-cols-2">
              {related.map((r) => (
                <a key={r.slug} href={hrefFor(`/khabar/${r.slug}`, lang)}
                   className="group flex gap-3 rounded-lg bg-white p-3 shadow-sm ring-1 ring-zinc-200 hover:shadow-md">
                  <div className="h-16 w-20 shrink-0 overflow-hidden rounded bg-zinc-100">
                    {r.image
                      ? <img src={r.image} alt="" loading="lazy" className="h-full w-full object-cover" />
                      : <div className="flex h-full items-center justify-center text-center text-[9px] font-semibold text-zinc-300">मुद्दा<br/>देश का</div>}
                  </div>
                  <div>
                    <h3 className="text-sm font-semibold leading-snug text-zinc-800 group-hover:text-brand-blue line-clamp-3">{r.ai_title || r.title}</h3>
                    <span className="mt-1 block text-[11px] text-zinc-400">{timeAgoHi(r.published_at)}</span>
                  </div>
                </a>
              ))}
            </div>
          </section>
        )}
      </main>

      <SiteFooter lang={lang} />
    </div>
  );
}
